title: NSMBW Speedrunning
description: Guides and resources for New Super Mario Bros. Wii speedrunning.
theme: just-the-docs
color_scheme: dark

markdown: kramdown
kramdown:
  parse_block_html: true

url: https://nsmbwcommunity.github.io
baseurl: /NSMBW-Speedrun-Guides

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

just_the_docs:
  custom_css:
    - custom/custom.scss

logo:
  image: assets/logos/icon128px.png
  alt: NSMBW Speedrunning Logo

favicon_ico: "/assets/logos/icon64px.png"