title: NSMBW Speedrunning
description: Guides and resources for New Super Mario Bros. Wii speedrunning.
theme: just-the-docs
color_scheme: dark

markdown: kramdown
kramdown:
  parse_block_html: true

url: https://nsmbwcommunity.github.io
baseurl: /NSMBW-Speedrun-Guides

just_the_docs:
  custom_css:
    - custom/custom.scss

logo: "assets/logos/icon128px.png"

favicon_ico: "/assets/logos/icon64px.png"